services:
  ollama: 
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434

  vector_db:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - 8000:8000